# Generated by Django 5.2.5 on 2025-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add a book'), ('can_change_book', 'Can edit a book'), ('can_delete_book', 'Can delete a book'))},
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2025-09-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
